# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_cap', models.CharField(max_length=128)),
                ('tm_cap2', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
