# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0002_auto_20160628_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel1',
            new_name='TestModel',
        ),
    ]
