# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-18 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0003_auto_20160628_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lkcm_budget_period',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='lkcm_budget_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
