# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0004_auto_20180718_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lkcm_dohod_rashod_type',
            field=models.CharField(choices=[(b'LKCM_DOHOD_RASHOD_TYPE_RASHOD', '\u0420\u0430\u0441\u0445\u043e\u0434'), (b'LKCM_DOHOD_RASHOD_TYPE_DOHOD', '\u0414\u043e\u0445\u043e\u0434')], default=b'LKCM_DOHOD_RASHOD_TYPE_RASHOD', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='lkcm_budget_period',
            field=models.CharField(blank=True, choices=[(b'LKCM_BUDGET_PERIOD_DAY', '\u0414\u0435\u043d\u044c'), (b'LKCM_BUDGET_PERIOD_WEEK', '\u041d\u0435\u0434\u0435\u043b\u044f'), (b'LKCM_BUDGET_PERIOD_MONTH', '\u041c\u0435\u0441\u044f\u0446'), (b'LKCM_BUDGET_PERIOD_QUART', '\u041a\u0432\u0430\u0440\u0442\u0430\u043b'), (b'LKCM_BUDGET_PERIOD_YEAR', '\u0413\u043e\u0434')], default=None, max_length=255, null=True),
        ),
    ]
