# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0005_auto_20181122_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchet',
            name='myum_time',
            field=models.TimeField(default=b'00:00'),
        ),
    ]
