# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0008_categorygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='visible',
            new_name='scf_visible',
        ),
    ]
