# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_uu', '0009_auto_20181219_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='scf_name',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('user', 'scf_name')]),
        ),
    ]
