# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_uu', '0010_auto_20181219_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='kgr_user',
            field=models.ForeignKey(default=702, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
