# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0011_categorygroup_kgr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scf_is_group',
            field=models.BooleanField(default=False),
        ),
    ]
