# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0012_category_scf_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygroup',
            name='kgr_user',
        ),
        migrations.AddField(
            model_name='category',
            name='scf_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_uu.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
