# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0013_auto_20181219_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scf_comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
