# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0014_category_scf_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scf_is_expanded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='scf_comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
