# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-27 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_uu', '0015_auto_20181223_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchet',
            name='myum_date_rep',
            field=models.DateField(default=None, help_text='\u0414\u0430\u0442\u0430 \u043e\u0442\u0447\u0451\u0442\u0430, \u0435\u0441\u043b\u0438 \u0437\u0430\u0434\u0430\u043d\u0430.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='scf_is_expanded',
            field=models.BooleanField(default=True, help_text='\n            \u041f\u0440\u0438\u0437\u043d\u0430\u043a \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0434\u043b\u044f \u0433\u0440\u0443\u043f\u043f.\n            \u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0410\u043d\u0430\u043b\u0438\u0437\u0430 - \u0441\u0432\u0435\u0440\u043d\u0443\u0442\u043e \u0438\u043b\u0438 \u0440\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u043e.\n        '),
        ),
    ]
